// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GameMatchesController from "./game_matches_controller"
application.register("game-matches", GameMatchesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
