// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ChifoumiSubscriptionController from "./chifoumi_subscription_controller"
application.register("chifoumi-subscription", ChifoumiSubscriptionController)

import DisplayChatController from "./display_chat_controller"
application.register("display-chat", DisplayChatController)

import GameMatchesController from "./game_matches_controller"
application.register("game-matches", GameMatchesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import JoinerListenerController from "./joiner_listener_controller"
application.register("joiner-listener", JoinerListenerController)

import ModalQuitController from "./modal_quit_controller"
application.register("modal-quit", ModalQuitController)

import RequestSubscriptionController from "./request_subscription_controller"
application.register("request-subscription", RequestSubscriptionController)

import ReturnGameMatchController from "./return_game_match_controller"
application.register("return-game-match", ReturnGameMatchController)

import TicTacToeGameSubscriptionController from "./tic_tac_toe_game_subscription_controller"
application.register("tic-tac-toe-game-subscription", TicTacToeGameSubscriptionController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
