// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TicTacToeGameSubscriptionController from "./tic_tac_toe_game_subscription_controller"
application.register("tic-tac-toe-game-subscription", TicTacToeGameSubscriptionController)
